name: 'Terraform'

on:
 push:
    branches: [ "main" ]
 pull_request:

jobs:
 terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: pr-sandboxapigee-alex
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set Google Cloud Credentials
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-sa-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=gcp-sa-key.json
        shell: bash


    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
